server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1057743499088-up1motjqo647pjg932jo7bkbuu4olvkm.apps.googleusercontent.com
            clientSecret: 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
  main:
      allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        show_sql: true
